# name: CICD

# on:
#   push:
#     branches: ["main"]
#   pull_request:
#     branches: ["main"]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Source
#         uses: actions/checkout@v4
#       - name: Login to Docker Hub
#         run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#       - name: Build Docker Image
#         run: docker build -t felixjayamuni/frontendrepo .
#       - name: Publish image to docker hub
#         run: docker push felixjayamuni/frontendrepo:latest

#   deploy:
#     needs: build
#     runs-on: aws-ec2
#     steps:
#       - name: Pull image from docker hub
#         run: docker pull felixjayamuni/frontendrepo:latest
#       - name: Delete old container
#         run: docker rm -f frontendContainer || true
#       - name: Run docker container
#         run: docker run -d -p 5176:80 --name frontendContainer felixjayamuni/frontendrepo

name: CICD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t felixjayamuni/frontendrepo .
      - name: Publish image to Docker Hub
        run: docker push felixjayamuni/frontendrepo:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from Docker Hub
        run: docker pull felixjayamuni/frontendrepo:latest

      - name: Delete old container (if exists)
        run: docker rm -f frontendContainer || true

      - name: Run Docker container in daemon mode
        run: docker run -d -p 5176:80 --name frontendContainer felixjayamuni/frontendrepo

      - name: Verify container is running
        run: |
          if [ "$(docker inspect -f '{{.State.Running}}' frontendContainer)" != "true" ]; then
            echo "Error: Container is not running!"
            exit 1
          fi
          echo "Container is running in daemon mode successfully."
